### ISSUE TITLE
Design Docs Review #1 

### ISSUE THREAD

**Issue by jliversi** [hquddus93/Trailmix#1]
Great start on your design docs! Just a few notes so far:
**MVP LIST** 
- [ ] Where will you build out your videos index? Will logged out users be able to see this?
- [x] For your videos index, will you have a "previously viewed" section?
- [x] Will you have a distinction between movies and shows? (Shows would have to be organized so that videos of the same show have some connection)

**SCHEMA** 
- [x] Is `my_list` just a joins table for videos and users? This is a fine way to implement it, but if so, we should remove the `my_list_id`s from the `users` table and the `videos` table, and just let those references exist on the `my_list` table
- [x] Do you need an entire directors table? If directors only exist to be a name on videos, can we just add this as a column on the videos table, `director_name`? 
- [x] As to the notes above, if you have a previously viewed section, you'll need some table to track this.
- [x] If you include shows, and distinguish them from movies, you'll probably need a shows table pointed to by a foreign key on the videos table (it would be null when the video is a movie).

**Comment by hquddus93** [comment]
I wasn't planning on allowing users to watch videos unless they are logged in. I believe this is how netflix operates as well. As for the other points I updated my schema/mvp -totally didn't think about the previously viewed table so I added that as well as a shows table to differentiate between movies/shows.
